# Common aliases
alias ll='ls -lah --color=auto'
alias l='ls -lrth'
alias grep='grep --color=auto'
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'
alias cdw='cd /workspace'